package com.freeoneplus.quick_test.controller;

import com.freeoneplus.quick_test.pojo.BaseSchemaInfo;
import com.freeoneplus.quick_test.pojo.TableDataInfo;
import com.freeoneplus.quick_test.pojo.WebBaseSchemaInfo;
import com.freeoneplus.quick_test.service.DataGenerateService;
import com.freeoneplus.quick_test.utils.ConfigUtils;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.Map;

@Slf4j
@RestController
public class QuickTestController {

    @Autowired
    DataGenerateService dataGenerateService;

    @RequestMapping("/autoGenerateData")
    public void test(WebBaseSchemaInfo webBaseSchemaInfo) {
        log.info("-------------------------开始造数-------------------------");
        TableDataInfo dataInfo = new TableDataInfo(webBaseSchemaInfo.getTableName(), webBaseSchemaInfo.getTotalNum());
        ArrayList<TableDataInfo> list = new ArrayList<>();
        list.add(dataInfo);
        log.info("造数信息如下：" + "\n" +
                "数据库：" + webBaseSchemaInfo.getDbName() + "\n" +
                "表名：" + webBaseSchemaInfo.getTableName() + "\n" +
                "FE-Host：" + webBaseSchemaInfo.getFeHost() + "\n" +
                "BE-Host：" + webBaseSchemaInfo.getBeHost() + "\n" +
                "FE-Port：" + webBaseSchemaInfo.getFePort() + "\n" +
                "BE-Port：" + webBaseSchemaInfo.getBePort() + "\n" +
                "用户名：" + webBaseSchemaInfo.getUsername() + "\n" +
                "用户密码：" + webBaseSchemaInfo.getUsername() + "\n" +
                "造数总数："  + webBaseSchemaInfo.getTotalNum());
        dataGenerateService.analysisSchemaGenerateData(
                new BaseSchemaInfo(
                        webBaseSchemaInfo.getDbName(),
                        webBaseSchemaInfo.getFeHost(),
                        webBaseSchemaInfo.getFePort(),
                        webBaseSchemaInfo.getBeHost(),
                        webBaseSchemaInfo.getBePort(),
                        webBaseSchemaInfo.getUsername(),
                        webBaseSchemaInfo.getPassword()),
                        list
        );
        log.info("-------------------------造数结束-------------------------");
    }
}
