spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Syj123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql.freeoneplus.com:3306?quick_test
server:
  port: 2022