spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://doris-test.freeoneplus.com/:3306?quick_test
server:
  port: 8088